from handlers.cmd_help import *
from handlers.cmd_start import *
from handlers.cmd_reg import *
from handlers.cmd_info import *
from handlers.cmd_transfer import *
from handlers.cmd_balance import *
from handlers.cmd_casino import *
from handlers.cmd_data import *
from handlers.cmd_edit_money import *
from handlers.cmd_test import *
from handlers.cmd_set_admin import *
from handlers.admin_panel import *
