from handlers.user.cmd_help import *
from handlers.user.cmd_start import *
from handlers.user.cmd_reg import *
from handlers.user.cmd_info import *
from handlers.user.cmd_transfer import *
from handlers.user.cmd_balance import *
from handlers.user.cmd_casino import *
from handlers.admin.cmd_data import *
from handlers.admin.cmd_edit_money import *
from handlers.cmd_test import *
from handlers.admin.cmd_set_admin import *
from handlers.admin.admin_panel import *
